function myxlswrite_wp(file, wp)
rad2deg=180/pi;
m2NM=0.000539957;

delete file;
array(1,:)=[0 0 0 0 0 0 0 0 0 0 0 0 0];
for i=1:length(wp)
    array(i+1,:)= [i,wp(i).lon, wp(i).lat, wp(i).alt,...
                   wp(i).tas,wp(i).head,wp(i).gs,wp(i).track,wp(i).vr...
                   wp(i).wind,wp(i).wdir,wp(i).dist*m2NM,wp(i).time/60]; 
end
xlswrite(file,array);

end
% array(1,:)={'Waypoint  ';,...
%        'Longitude ';,...
%        'Latitude  ';,...
%        'Altitude  ';,...
%        'TAS       ';,...
%        'Heading   ';,...
%        'GS        ';,...
%        'Track     ';,...
%        'V/R       ';,...
%        'Wind speed';,...
%        'Wind dir. ';,...
%        'Distance  ';,...
%        'Time      '};


